### ISSUE TITLE
enrich configuration per template set by further meta data like human readable name and description

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1463]
* [x] add descriptions of the template set
* [x] add description of increments
* [x] tags for which type of generation is done (input file type e.g. entity, output language e.g. java, framework usage e.g. angular)
* [x] links to guides/tutorials regarding the relevant template set
* [x] adapt xsd to be able to add all the above to the config

**Comment by MikeSchumacherCapgemini** [comment]
Things we should add to the config/change about them:
- add descriptions of the template set and increments
- merge templates.xml and context.xml into 1 file

**Comment by MikeSchumacherCapgemini** [comment]
Things we could add/change:
- tags for which type of generation is done (input file type e.g. entity, output language e.g. java, framework usage e.g. angular)
- plugins necessary for generation
- links to guides/tutorials regarding the relevant template set

**Comment by mdukhan** [comment]
Descriptions + tutorials we could add: 

1-**crud_angular_client_app**
Increment Description: CRUD devon4ng Angular App
Description: create Angular stack crud service 
TutorialLink:
https://github.com/devonfw/cobigen/wiki/howto_angular-client-generation

-----------------------------
2-**crud_ionic_client_app**
Increment Description: CRUD devon4ng Ionic App
Description: create Ionic stack crud service 
TutorialLink:
https://github.com/devonfw/cobigen/wiki/howto_ionic-client-generation

-----------------------------
3-**crud_java_ea_uml**
Increment Description: Entity infrastructure
Description: create Entity java classes to crud from schema
TutorialLink:

-----------------------------
4-**crud_java_server_app**
Increment Description: CRUD SpringData Repository
Description: create (backends ) spring server crud service for java
TutorialLink: 

-----------------------------
5-**crud_java_server_app_complex**
Increment Description: CRUD UC logic
Description: create (backends) server crud service for java
TutorialLink:

-----------------------------
6-**crud_ngrx_client_app**
Increment Description: Angular CRUD rxjs App
Description: create Angular stack crud service  for rxjs Application
TutorialLink:
https://rxjs.dev/api

-----------------------------
7-**crud_openapi_angular_client_app**
Increment Description: CRUD devon4ng Angular App
Description: create Angular stack crud service 
TutorialLink:

-----------------------------
8-**crud_openapi_angular_service_based_app**
Increment Description: CRUD devon4ng Service Based Angular
Description: create Angular stack crud service 
TutorialLink:

-----------------------------
9-**crud_openapi_ionic_client_app**
Increment Description: CRUD devon4ng Ionic App
Description: create Ionic stack crud service 
TutorialLink:
https://github.com/devonfw/cobigen/wiki/howto-devonfw-CobiGen-OpenAPI

-----------------------------
10-**crud_openapi_java_server_app**
Increment Description: CRUD devon4j Server
Description: create (backends) server crud service for java
TutorialLink:
https://github.com/devonfw/cobigen/wiki/howto-devonfw-ide-CobiGen-PoC-E2E

-----------------------------
11-**crud_openapi_net**
Increment Description: CRUD devon4net Server
Description: create (backends) server crud service for .Net application
TutorialLink:
https://github.com/devonfw/cobigen/wiki/howto_devon4net

-----------------------------
12-**crud_typescript_angular_client_app**
Increment Description: CRUD devon4ng Angular App
Description: create Angular stack crud service 
TutorialLink:

-----------------------------
13-**kafka_documentation**
Increment Description: Documentation
Description: contains information about the operations of the ${variables.domain} for kafka application
TutorialLink:
https://kafka.apache.org/documentation/

-----------------------------
14-**named_queries**
Increment Description: Named Query Constants
Description: generate basic querey constants schema 
TutorialLink:

-----------------------------
15-**openapi_documentation**
Increment Description: Documentation
Description: contains information about the operations of the ${model.header.info.title} application.
TutorialLink:
https://github.com/devonfw/cobigen/wiki/cobigen-openapiplugin

-----------------------------
16-**rest_documentation**
Increment Description: Documentation
Description: contains information about the operations of the ${variables.domain} application.
TutorialLink:

-----------------------------
17-**security_permissions**
Increment Description: Permission Constants
Description: 
TutorialLink:

-----------------------------
18-**testdata_builder**
Increment Description: Testdata builder
Description: 
TutorialLink:
