### ISSUE TITLE
complete cobigen-eclipse release v1.1.0

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#42]
**Tasks:**
- [x] Integrate cobigen-core v1.1.0
- [x] Integrate cobigen-javaplugin v1.1.1
- [x] Integrate cobigen-xmlplugin v1.0.1

**Release tasks:**
**_1. Preparation**_
- [x] Check for changed dependencies and document them if necessary (especially if internal cobigen dependendencies have been changed). _As dependencies have been changed:_
  - [x] check new dependencies with legal and create new licensing document for new version
  - [x] document the changes in the [ChangeLog of the dependency tracking](https://github.com/oasp/tools-cobigen/wiki/mgmt_deployment).
- [x] Check running maven build
- [x] Check if all tests are green and if there are no ignored ones left. As there are ignored ones, please check them if they can be removed or they only should be temporarily ignored. In the latter case fix them!
- [x] Deploy snapshot build to OASP Nexus

**_2. Merging**_
- [x] Merge development branch to master branch
  - [x] Perform final Review of merged contents
    - if ok - push
    - if not - abort merge and fix on dev branch
- [x] higher version number to release version

**_3. Testing / Consolidation**_
- [x] Perform integration tests
  - especially for cobigen-eclipse if cobigen internal dependencies have been changed
- [x] Check/Update documentation according to changelog to be released

**_4. Deployment**_
- [x] Create a tag according to the naming conventions
- [x] Deploy release build to OASP Nexus
- [x] Deploy release build to network drive
- [x] Close milestone and create new release on GitHub

**_5. Follow-up**_
- [x] Merge master branch back to development branch which previously had been merged into master
