### ISSUE TITLE
Create generic xml input reader

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#50]
We should create a generic xml input reader, which traverses the input xml and creates a similar object model out of it.
Example:

``` xml
<root>
  <test attr="abc"/>
</root>
```

The attribute `attr` should be accessible in the object model using `${root.test.@attr}` and also by

```
<#list root.testList as test>
${test.@attr}
</#list>
```

The first "simple" variable access should be only available if the document declares only one `<test>` node as in the example. But you might also imagine to have a document like this:

``` xml
<root>
  <test attr="abc"/>
  <test attr="efg"/>
</root>
```

As we do not know the schema definition of the input xml, we do not know whether we should provide a list of nodes or a single variable path for the node access. So in general we should provide a list for every node besides the root node to be as generic as possible.

This issue has been motivated by oasp/oasp4j#77

**Tasks:**
- [x] refactor tests to match latest test distinction pattern equivalently as on dev_javaplugin
- [x] Implement model transformation nodes -> template
- [x] implement attribute retrieval using `*.@attr` syntax
- [x] implement PCDATA retrieval using `*.#` syntax
- [x] add documentation in the wiki
- [x] update changed dependencies
